import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { GasStationOrderByWithRelationInputObjectSchema as GasStationOrderByWithRelationInputObjectSchema } from './objects/GasStationOrderByWithRelationInput.schema';
import { GasStationWhereInputObjectSchema as GasStationWhereInputObjectSchema } from './objects/GasStationWhereInput.schema';
import { GasStationWhereUniqueInputObjectSchema as GasStationWhereUniqueInputObjectSchema } from './objects/GasStationWhereUniqueInput.schema';
import { GasStationCountAggregateInputObjectSchema as GasStationCountAggregateInputObjectSchema } from './objects/GasStationCountAggregateInput.schema';
import { GasStationMinAggregateInputObjectSchema as GasStationMinAggregateInputObjectSchema } from './objects/GasStationMinAggregateInput.schema';
import { GasStationMaxAggregateInputObjectSchema as GasStationMaxAggregateInputObjectSchema } from './objects/GasStationMaxAggregateInput.schema';
import { GasStationAvgAggregateInputObjectSchema as GasStationAvgAggregateInputObjectSchema } from './objects/GasStationAvgAggregateInput.schema';
import { GasStationSumAggregateInputObjectSchema as GasStationSumAggregateInputObjectSchema } from './objects/GasStationSumAggregateInput.schema';

export const GasStationAggregateSchema: z.ZodType<Prisma.GasStationAggregateArgs> = z.object({ orderBy: z.union([GasStationOrderByWithRelationInputObjectSchema, GasStationOrderByWithRelationInputObjectSchema.array()]).optional(), where: GasStationWhereInputObjectSchema.optional(), cursor: GasStationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), GasStationCountAggregateInputObjectSchema ]).optional(), _min: GasStationMinAggregateInputObjectSchema.optional(), _max: GasStationMaxAggregateInputObjectSchema.optional(), _avg: GasStationAvgAggregateInputObjectSchema.optional(), _sum: GasStationSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.GasStationAggregateArgs>;

export const GasStationAggregateZodSchema = z.object({ orderBy: z.union([GasStationOrderByWithRelationInputObjectSchema, GasStationOrderByWithRelationInputObjectSchema.array()]).optional(), where: GasStationWhereInputObjectSchema.optional(), cursor: GasStationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), GasStationCountAggregateInputObjectSchema ]).optional(), _min: GasStationMinAggregateInputObjectSchema.optional(), _max: GasStationMaxAggregateInputObjectSchema.optional(), _avg: GasStationAvgAggregateInputObjectSchema.optional(), _sum: GasStationSumAggregateInputObjectSchema.optional() }).strict();