import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ClassificationOrderByWithRelationInputObjectSchema as ClassificationOrderByWithRelationInputObjectSchema } from './objects/ClassificationOrderByWithRelationInput.schema';
import { ClassificationWhereInputObjectSchema as ClassificationWhereInputObjectSchema } from './objects/ClassificationWhereInput.schema';
import { ClassificationWhereUniqueInputObjectSchema as ClassificationWhereUniqueInputObjectSchema } from './objects/ClassificationWhereUniqueInput.schema';
import { ClassificationCountAggregateInputObjectSchema as ClassificationCountAggregateInputObjectSchema } from './objects/ClassificationCountAggregateInput.schema';
import { ClassificationMinAggregateInputObjectSchema as ClassificationMinAggregateInputObjectSchema } from './objects/ClassificationMinAggregateInput.schema';
import { ClassificationMaxAggregateInputObjectSchema as ClassificationMaxAggregateInputObjectSchema } from './objects/ClassificationMaxAggregateInput.schema';
import { ClassificationAvgAggregateInputObjectSchema as ClassificationAvgAggregateInputObjectSchema } from './objects/ClassificationAvgAggregateInput.schema';
import { ClassificationSumAggregateInputObjectSchema as ClassificationSumAggregateInputObjectSchema } from './objects/ClassificationSumAggregateInput.schema';

export const ClassificationAggregateSchema: z.ZodType<Prisma.ClassificationAggregateArgs> = z.object({ orderBy: z.union([ClassificationOrderByWithRelationInputObjectSchema, ClassificationOrderByWithRelationInputObjectSchema.array()]).optional(), where: ClassificationWhereInputObjectSchema.optional(), cursor: ClassificationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ClassificationCountAggregateInputObjectSchema ]).optional(), _min: ClassificationMinAggregateInputObjectSchema.optional(), _max: ClassificationMaxAggregateInputObjectSchema.optional(), _avg: ClassificationAvgAggregateInputObjectSchema.optional(), _sum: ClassificationSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ClassificationAggregateArgs>;

export const ClassificationAggregateZodSchema = z.object({ orderBy: z.union([ClassificationOrderByWithRelationInputObjectSchema, ClassificationOrderByWithRelationInputObjectSchema.array()]).optional(), where: ClassificationWhereInputObjectSchema.optional(), cursor: ClassificationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ClassificationCountAggregateInputObjectSchema ]).optional(), _min: ClassificationMinAggregateInputObjectSchema.optional(), _max: ClassificationMaxAggregateInputObjectSchema.optional(), _avg: ClassificationAvgAggregateInputObjectSchema.optional(), _sum: ClassificationSumAggregateInputObjectSchema.optional() }).strict();