import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { GasSupplyOrderByWithRelationInputObjectSchema as GasSupplyOrderByWithRelationInputObjectSchema } from './objects/GasSupplyOrderByWithRelationInput.schema';
import { GasSupplyWhereInputObjectSchema as GasSupplyWhereInputObjectSchema } from './objects/GasSupplyWhereInput.schema';
import { GasSupplyWhereUniqueInputObjectSchema as GasSupplyWhereUniqueInputObjectSchema } from './objects/GasSupplyWhereUniqueInput.schema';
import { GasSupplyCountAggregateInputObjectSchema as GasSupplyCountAggregateInputObjectSchema } from './objects/GasSupplyCountAggregateInput.schema';
import { GasSupplyMinAggregateInputObjectSchema as GasSupplyMinAggregateInputObjectSchema } from './objects/GasSupplyMinAggregateInput.schema';
import { GasSupplyMaxAggregateInputObjectSchema as GasSupplyMaxAggregateInputObjectSchema } from './objects/GasSupplyMaxAggregateInput.schema';
import { GasSupplyAvgAggregateInputObjectSchema as GasSupplyAvgAggregateInputObjectSchema } from './objects/GasSupplyAvgAggregateInput.schema';
import { GasSupplySumAggregateInputObjectSchema as GasSupplySumAggregateInputObjectSchema } from './objects/GasSupplySumAggregateInput.schema';

export const GasSupplyAggregateSchema: z.ZodType<Prisma.GasSupplyAggregateArgs> = z.object({ orderBy: z.union([GasSupplyOrderByWithRelationInputObjectSchema, GasSupplyOrderByWithRelationInputObjectSchema.array()]).optional(), where: GasSupplyWhereInputObjectSchema.optional(), cursor: GasSupplyWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), GasSupplyCountAggregateInputObjectSchema ]).optional(), _min: GasSupplyMinAggregateInputObjectSchema.optional(), _max: GasSupplyMaxAggregateInputObjectSchema.optional(), _avg: GasSupplyAvgAggregateInputObjectSchema.optional(), _sum: GasSupplySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.GasSupplyAggregateArgs>;

export const GasSupplyAggregateZodSchema = z.object({ orderBy: z.union([GasSupplyOrderByWithRelationInputObjectSchema, GasSupplyOrderByWithRelationInputObjectSchema.array()]).optional(), where: GasSupplyWhereInputObjectSchema.optional(), cursor: GasSupplyWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), GasSupplyCountAggregateInputObjectSchema ]).optional(), _min: GasSupplyMinAggregateInputObjectSchema.optional(), _max: GasSupplyMaxAggregateInputObjectSchema.optional(), _avg: GasSupplyAvgAggregateInputObjectSchema.optional(), _sum: GasSupplySumAggregateInputObjectSchema.optional() }).strict();