import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { DocumentationOrderByWithRelationInputObjectSchema as DocumentationOrderByWithRelationInputObjectSchema } from './objects/DocumentationOrderByWithRelationInput.schema';
import { DocumentationWhereInputObjectSchema as DocumentationWhereInputObjectSchema } from './objects/DocumentationWhereInput.schema';
import { DocumentationWhereUniqueInputObjectSchema as DocumentationWhereUniqueInputObjectSchema } from './objects/DocumentationWhereUniqueInput.schema';
import { DocumentationCountAggregateInputObjectSchema as DocumentationCountAggregateInputObjectSchema } from './objects/DocumentationCountAggregateInput.schema';
import { DocumentationMinAggregateInputObjectSchema as DocumentationMinAggregateInputObjectSchema } from './objects/DocumentationMinAggregateInput.schema';
import { DocumentationMaxAggregateInputObjectSchema as DocumentationMaxAggregateInputObjectSchema } from './objects/DocumentationMaxAggregateInput.schema';
import { DocumentationAvgAggregateInputObjectSchema as DocumentationAvgAggregateInputObjectSchema } from './objects/DocumentationAvgAggregateInput.schema';
import { DocumentationSumAggregateInputObjectSchema as DocumentationSumAggregateInputObjectSchema } from './objects/DocumentationSumAggregateInput.schema';

export const DocumentationAggregateSchema: z.ZodType<Prisma.DocumentationAggregateArgs> = z.object({ orderBy: z.union([DocumentationOrderByWithRelationInputObjectSchema, DocumentationOrderByWithRelationInputObjectSchema.array()]).optional(), where: DocumentationWhereInputObjectSchema.optional(), cursor: DocumentationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DocumentationCountAggregateInputObjectSchema ]).optional(), _min: DocumentationMinAggregateInputObjectSchema.optional(), _max: DocumentationMaxAggregateInputObjectSchema.optional(), _avg: DocumentationAvgAggregateInputObjectSchema.optional(), _sum: DocumentationSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.DocumentationAggregateArgs>;

export const DocumentationAggregateZodSchema = z.object({ orderBy: z.union([DocumentationOrderByWithRelationInputObjectSchema, DocumentationOrderByWithRelationInputObjectSchema.array()]).optional(), where: DocumentationWhereInputObjectSchema.optional(), cursor: DocumentationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DocumentationCountAggregateInputObjectSchema ]).optional(), _min: DocumentationMinAggregateInputObjectSchema.optional(), _max: DocumentationMaxAggregateInputObjectSchema.optional(), _avg: DocumentationAvgAggregateInputObjectSchema.optional(), _sum: DocumentationSumAggregateInputObjectSchema.optional() }).strict();