import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ClassificationWhereInputObjectSchema as ClassificationWhereInputObjectSchema } from './objects/ClassificationWhereInput.schema';
import { ClassificationOrderByWithAggregationInputObjectSchema as ClassificationOrderByWithAggregationInputObjectSchema } from './objects/ClassificationOrderByWithAggregationInput.schema';
import { ClassificationScalarWhereWithAggregatesInputObjectSchema as ClassificationScalarWhereWithAggregatesInputObjectSchema } from './objects/ClassificationScalarWhereWithAggregatesInput.schema';
import { ClassificationScalarFieldEnumSchema } from './enums/ClassificationScalarFieldEnum.schema';
import { ClassificationCountAggregateInputObjectSchema as ClassificationCountAggregateInputObjectSchema } from './objects/ClassificationCountAggregateInput.schema';
import { ClassificationMinAggregateInputObjectSchema as ClassificationMinAggregateInputObjectSchema } from './objects/ClassificationMinAggregateInput.schema';
import { ClassificationMaxAggregateInputObjectSchema as ClassificationMaxAggregateInputObjectSchema } from './objects/ClassificationMaxAggregateInput.schema';
import { ClassificationAvgAggregateInputObjectSchema as ClassificationAvgAggregateInputObjectSchema } from './objects/ClassificationAvgAggregateInput.schema';
import { ClassificationSumAggregateInputObjectSchema as ClassificationSumAggregateInputObjectSchema } from './objects/ClassificationSumAggregateInput.schema';

export const ClassificationGroupBySchema: z.ZodType<Prisma.ClassificationGroupByArgs> = z.object({ where: ClassificationWhereInputObjectSchema.optional(), orderBy: z.union([ClassificationOrderByWithAggregationInputObjectSchema, ClassificationOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ClassificationScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ClassificationScalarFieldEnumSchema), _count: z.union([ z.literal(true), ClassificationCountAggregateInputObjectSchema ]).optional(), _min: ClassificationMinAggregateInputObjectSchema.optional(), _max: ClassificationMaxAggregateInputObjectSchema.optional(), _avg: ClassificationAvgAggregateInputObjectSchema.optional(), _sum: ClassificationSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ClassificationGroupByArgs>;

export const ClassificationGroupByZodSchema = z.object({ where: ClassificationWhereInputObjectSchema.optional(), orderBy: z.union([ClassificationOrderByWithAggregationInputObjectSchema, ClassificationOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ClassificationScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ClassificationScalarFieldEnumSchema), _count: z.union([ z.literal(true), ClassificationCountAggregateInputObjectSchema ]).optional(), _min: ClassificationMinAggregateInputObjectSchema.optional(), _max: ClassificationMaxAggregateInputObjectSchema.optional(), _avg: ClassificationAvgAggregateInputObjectSchema.optional(), _sum: ClassificationSumAggregateInputObjectSchema.optional() }).strict();