import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { GasSupplyWhereInputObjectSchema as GasSupplyWhereInputObjectSchema } from './objects/GasSupplyWhereInput.schema';
import { GasSupplyOrderByWithAggregationInputObjectSchema as GasSupplyOrderByWithAggregationInputObjectSchema } from './objects/GasSupplyOrderByWithAggregationInput.schema';
import { GasSupplyScalarWhereWithAggregatesInputObjectSchema as GasSupplyScalarWhereWithAggregatesInputObjectSchema } from './objects/GasSupplyScalarWhereWithAggregatesInput.schema';
import { GasSupplyScalarFieldEnumSchema } from './enums/GasSupplyScalarFieldEnum.schema';
import { GasSupplyCountAggregateInputObjectSchema as GasSupplyCountAggregateInputObjectSchema } from './objects/GasSupplyCountAggregateInput.schema';
import { GasSupplyMinAggregateInputObjectSchema as GasSupplyMinAggregateInputObjectSchema } from './objects/GasSupplyMinAggregateInput.schema';
import { GasSupplyMaxAggregateInputObjectSchema as GasSupplyMaxAggregateInputObjectSchema } from './objects/GasSupplyMaxAggregateInput.schema';
import { GasSupplyAvgAggregateInputObjectSchema as GasSupplyAvgAggregateInputObjectSchema } from './objects/GasSupplyAvgAggregateInput.schema';
import { GasSupplySumAggregateInputObjectSchema as GasSupplySumAggregateInputObjectSchema } from './objects/GasSupplySumAggregateInput.schema';

export const GasSupplyGroupBySchema: z.ZodType<Prisma.GasSupplyGroupByArgs> = z.object({ where: GasSupplyWhereInputObjectSchema.optional(), orderBy: z.union([GasSupplyOrderByWithAggregationInputObjectSchema, GasSupplyOrderByWithAggregationInputObjectSchema.array()]).optional(), having: GasSupplyScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(GasSupplyScalarFieldEnumSchema), _count: z.union([ z.literal(true), GasSupplyCountAggregateInputObjectSchema ]).optional(), _min: GasSupplyMinAggregateInputObjectSchema.optional(), _max: GasSupplyMaxAggregateInputObjectSchema.optional(), _avg: GasSupplyAvgAggregateInputObjectSchema.optional(), _sum: GasSupplySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.GasSupplyGroupByArgs>;

export const GasSupplyGroupByZodSchema = z.object({ where: GasSupplyWhereInputObjectSchema.optional(), orderBy: z.union([GasSupplyOrderByWithAggregationInputObjectSchema, GasSupplyOrderByWithAggregationInputObjectSchema.array()]).optional(), having: GasSupplyScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(GasSupplyScalarFieldEnumSchema), _count: z.union([ z.literal(true), GasSupplyCountAggregateInputObjectSchema ]).optional(), _min: GasSupplyMinAggregateInputObjectSchema.optional(), _max: GasSupplyMaxAggregateInputObjectSchema.optional(), _avg: GasSupplyAvgAggregateInputObjectSchema.optional(), _sum: GasSupplySumAggregateInputObjectSchema.optional() }).strict();